### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by joe9** [tuxmark5/EnableRazer#1]
cabal install  
Resolving dependencies...  
Configuring EnableRazer-0.0.1...  
Building EnableRazer-0.0.1...  
Preprocessing executable 'EnableRazer' for EnableRazer-0.0.1...  
[1 of 1] Compiling Main             ( src/Main.hs, dist/build/EnableRaz
er/EnableRazer-tmp/Main.o )                                            

src/Main.hs:40:19:  
    Not in scope: `deviceDesc'                                         
    Perhaps you meant`devDesc' (line 40)  
Failed to install EnableRazer-0.0.1  
cabal: Error: some packages failed to install:  
EnableRazer-0.0.1 failed during the building phase. The exception was: 
ExitFailure 1

**Comment by tuxmark5** [comment]
I fixed this problem in the latest commit.

**Comment by joe9** [comment]
I forked your code and added the fix too at
https://github.com/joe9/EnableRazer. It works too.

**Comment by tuxmark5** [comment]
I added multiple product ids support, so it wouldn't be necessary to maintain two separate versions of almost identical code. Now the program works with both BlackWidow Stealth and your id as well (0x010e, whatever product that is)

**Comment by joe9** [comment]
Ok, Thanks for your prompt response.

**Comment by joe9** [comment]
These warnings are fixed in my fork. Would you mind patching yours to avoid
these warnings?

ghci -Wall Main.hs
GHCi, version 7.6.2: http://www.haskell.org/ghc/  :? for help
Loading package ghc-prim ... linking ... done.
Loading package integer-gmp ... linking ... done.
Loading package base ... linking ... done.
(0.00 secs, 515512 bytes)
(0.00 secs, 557864 bytes)
(0.00 secs, 1055672 bytes)
(0.00 secs, 507872 bytes)
(0.00 secs, 555320 bytes)
[1 of 1] Compiling Main             ( Main.hs, interpreted )

Main.hs:3:1: Warning:
    The qualified import of `BS.unpack, BS.length, BS.empty'
    from module`Data.ByteString' is redundant

Main.hs:4:1: Warning:
    The import of `Data.List' is redundant
      except perhaps to import instances from`Data.List'
    To import instances alone, use: import Data.List()

Main.hs:7:1: Warning:
    The import of `System.IO' is redundant
      except perhaps to import instances from`System.IO'
    To import instances alone, use: import System.IO()

Main.hs:10:1: Warning:
    Top-level binding with no type signature: _SET_REPORT :: Request

Main.hs:75:15: Warning: Defined but not used: `a'
Ok, modules loaded: Main.
(0.13 secs, 64718000 bytes)

Thanks
Joe

**Comment by tuxmark5** [comment]
I've just commited a patch that fixes these warnings.

**Comment by joe9** [comment]
Thanks.

**Comment by tuxmark5** [comment]
No problem :)
