### ISSUE TITLE
Distribution & Licensing

### ISSUE THREAD

**Issue by wraeth** [tuxmark5/EnableRazer#2]
Greetings;

I found this useful and got it working for my Razer Anansi with only a modification to the product id value (can provide patch if requested). I would like to wrap the compile/installation of this utility for distribution on Gentoo, and was wondering:

a) if you would be opposed to this; and
b) what your opinion on licensing was

Cheers

**Comment by tuxmark5** [comment]
Feel free to redistribute and modify the code in any way you want.
As for licensing, I usually prefer more liberal licenses like LGPL/BSD.

However if you add some significant improvements to the code, I'd love to merge them to the main branch, so other people may benefit from this as well. But this is up to you :)

**Comment by tuxmark5** [comment]
Thanks for the patch! :)

**Comment by wraeth** [comment]
No worries. :)
